version: '3.5'
services:
#
# IREDMAIL
#
  iredmail:
    image: lejmr/iredmail:mysql-latest
    restart: unless-stopped
    container_name: iredmail
    hostname: mail
    domainname: marche.com.hk
    environment:
      - DOMAIN=marche.com.hk
      - HOSTNAME=mail
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXXXX
      - SOGO_WORKERS=1
      - TIMEZONE=Asia/Hong_Kong
      - POSTMASTER_PASSWORD={PLAIN}mc@24949981
      - IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_acce>
    volumes:
      - iredmail-mysql:/var/lib/mysql
      - iredmail-vmail:/var/vmail
      - iredmail-clamav:/var/lib/clamav
      - ~/<source_folder>/privkey.pem:/etc/ssl/private/iRedMail.key:ro
      - ~/<source_folder>/fullchain.pem:/etc/ssl/certs/iRedMail.crt:ro
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
#
# VOLUMES
#
volumes:
  iredmail-mysql:
  iredmail-vmail:
  iredmail-clamav:
